### ISSUE TITLE
Errors in code to solve Coin Change Problem

### ISSUE THREAD

**Issue by howsiwei** [patrickt/recschemes#1]
Hi, I stumbled upon your intro series to recursion schemes and so far it is an enlightening read. However, I notice that there are some errors in the code for Coin Change Problem in part 4 of the series.

First, normally Coin Change Problem asks for the number of ways one can make the change of a fixed amount that is insensitive to the order where a coin is being listed. Eg. there are only 2 ways to make a change of amount 6:
[1, 5]
[1, 1, 1, 1, 1, 1]
Note that here [1, 5] and [5, 1] are counted as the same way.

However, the intention of your code seems to be sensitive to the order of the coins. Eg. there are 3 ways to make a change of amount 6:
[1, 5]
[5, 1]
[1, 1, 1, 1, 1, 1]

Secondly, the code to lookup cache is wrong. The code seems to incorrectly assume that the history is stored in such a way that the result of `change 0` is stored at the outermost level, result of `change 1` is stored at the second outermost level, ..., and the result of `change (given - 1)` is stored at the innermost level. However, the reverse is true. That is, the result of `change (given - 1)` is stored at the outermost level and the result of `change 0` is stored at the innermost level.

Below is a modified code that correctly solves the Coin Change Problem variant where the order of the coins in the change matters.
```haskell
change :: Cent -> Int
change amt = histo go (expand amt) where
  go :: Nat (Attr Nat Int) -> Int
  go Zero = 1
  go curr@(Next attr) = let
    given = compress curr
    validCoins = filter (<= given) coins
    in sum (map (lookup attr) validCoins)

lookup :: Attr Nat a -> Int -> a
lookup cache 1 = attribute cache
lookup cache n = lookup inner (n - 1) where (Next inner) = hole cache
```

**Comment by patrickt** [comment]
Thank you so much! You're absolutely right. I had a suspicion something was off about my implementation but was unable to nail it down. I'll make these changes as soon as I'm able.

**Comment by Ptival** [comment]
Ha! I came to the same conclusions on my own and was about to post an issue here to let you know! :-)

Excellent blog post series nonetheless!

**Comment by patrickt** [comment]
@howsiwei I’ve fixed this in the blog entry and credited you. Thank you so much!
