### ISSUE TITLE
Typos in the futumorphism section of Part 4

### ISSUE THREAD

**Issue by jlavelle** [patrickt/recschemes#2]
Thank you for writing this excellent series!  

I noticed that starting around [here](https://github.com/patrickt/recschemes/blob/master/src/Part4.lhs#L752]) you start using `Continue` and `Stop` to refer to the `CoAttr` constructors in the text and in parts of the horticulture example code, whereas you have defined these constructors as `Automatic` and `Manual`.

**Comment by fragilelambda** [comment]
Also in [here](https://github.com/patrickt/recschemes/blob/a0faf2797e8a196e77ae0ae31fb5dac0aec523fc/src/Part4.lhs#L319) and [here](https://github.com/patrickt/recschemes/blob/a0faf2797e8a196e77ae0ae31fb5dac0aec523fc/src/Part4.lhs#L305), the term seems to be t.
